feat(common): DATA-000 Add header for all requests from Control Panel
bigcommerce/request-sender-js pull request #45
Opened 2022-04-19 13:55 UTC by bc-rmalyavc

## What?
Add "isControlPanel" param to add a default header for all requests from Control Panel.
This PR is related to another PR in bcapp (see below).
https://github.com/bigcommerce/bigcommerce/pull/45966
This is how we are planning to use this approach

## Why?
We previously had a method in bcapp to define Control Panel requests, but it's working based on the url, and this is not reliable anymore, since we are mostly using micro app approach. This additional header seems to be a good approach to define Control Panel requests

## Testing / Proof
Manually tested

@bigcommerce/frontend

2022-04-19 14:43 UTC, rtalvarez reviewed
You might want to either add `.idea` to `.gitignore` or remove the files from this PR

Also not quite sure why `package-lock.json` got updated, you don't seem to be updating any deps. Might want to double check that too

2022-04-19 15:15 UTC, jorgemoya commented
I second @rtalvarez's concerns.

2022-04-19 15:18 UTC, jorgemoya commented on src/request-sender.ts
> +            defaultOptions.headers[this.CONTROL_PANEL_HEADER] = true;
Just in line the header.

```suggestion
            defaultOptions.headers['X-CONTROL-PANEL-REQUEST'] = true;
```

2022-04-19 15:27 UTC, jorgemoya commented
I still wonder if there is a better way to do this other than an option value but I have 0 context.

2022-04-19 15:45 UTC, bc-rmalyavc commented
> I still wonder if there is a better way to do this other than an option value but I have 0 context.

Hi @jorgemoya,
Thanks for your review!
To give you some context. We've got this API endpoint in bcapp /internalapi/v1/settings/analytics. We now have a requirement to track requests to this API and also to define, from where the request was sent (Control Panel, External API call, call from mobile device). Currently we don't have way to distinguish external API call from call from our Control Panel. That's why we need this header. If you have any other ideas how else we can do it, please share with me)

2022-04-19 22:20 UTC, icatalina commented
Let's try and continue the conversation in the bigcommerce PR.

2022-04-20 14:25 UTC, icatalina commented
Blocking this as the sibling PR was merged without finishing the conversation.

2022-04-20 14:26 UTC, icatalina requested changes
Blocking this as the sibling PR was merged without finishing the conversation.

2022-04-20 14:59 UTC, solofeed commented
@icatalina Hi. We merged PR by accident, we will try to check the store cp token header to decide, if this request was from CP.
So we don't need to change logic here yet.

2022-04-20 18:37 UTC, bc-rmalyavc commented
This PR is not needed anymore as we found another way to distinguish Control Panel API calls from calls from API account. Thanks everyone for your help!

2022-04-20 18:37 UTC, closed without merging